name: Generate pacman contribution graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: tanishbhandari11t
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-dark
            dist/pacman-contribution-graph-dark.svg?palette=github-dark
          snake_color: "#ffb300"
          dot1_color: "#ff0000"
          dot2_color: "#ff6600"
          dot3_color: "#ffcc00"
          dot4_color: "#00ff00"
          dot5_color: "#0099ff"

      - name: push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
